version: '3'
services: 
  redis-server: 
    image: 'redis'
  node-app: 
    restart: on-failure
    build: .
    ports: 
      - "4001:8081" #4001 local. 8081 on container + it automatically route network btw containers